### ISSUE TITLE
Why you didn't use avg pool in SeModule?

### ISSUE THREAD

**Issue by PistonY** [xiaolai-sqlai/mobilenetv3#3]
https://github.com/xiaolai-sqlai/mobilenetv3/blob/5ec8ae3386c3f8268e2d79a61017fc13db051885/mobilenetv3.py#L28

**Comment by PistonY** [comment]
You just define it but never use.

**Comment by BowieHsu** [comment]
maybe it's a mistake

**Comment by PistonY** [comment]
LOL, you implement a pixel level attention by mistake.

**Comment by BowieHsu** [comment]
@PistonY hey, easy, man, i just mean maybe it's legacy code, after all there is no static check for pytorch code.

**Comment by PistonY** [comment]
HaHa
